### ISSUE TITLE
propose change to PR review requirements

### ISSUE THREAD

**Issue by batmany13** [SYNQfm/getting-started#27]
I'd like to propose we change our review requirements criteria.  In the interest of speeding up deploy cycles, I'd like to suggest these changes

* PR reviews are no longer mandatory
* Tagging a PR with a reviewer is still mandatory
* PR Review is a courtesy review and the reviewer has up to 1 day to make his/her comments, after which the PR person can merge the changes in themselves.
* Changes that are commented on a PR will be reviewed and turned into issues that can be worked on (could be something as simple as "PR improvements")
* Tests and coverage of > 75% is required (unless its first couple of initial commits)
* Push to include Runscope "system" tests against continuously integrated repos
* Periodic code reviews, which will be a deeper dive, will take place every month or so.  Anyone can propose a code review, either the code owner or someone else

**Comment by paltorg** [comment]
We definitely need to speed up the reviews. It is currently affecting our productivity level alot!

**Comment by paltorg** [comment]
So @martinatsynqfm will follow the new suggested PR review requirements (https://github.com/SYNQfm/getting-started/issues/27) for the Hydra PRs. Review will be finished today so that you are able to test @batmany13 .  We will do a thorough code review at a suggested time later as proposed in the last bullet.

**Comment by batmany13** [comment]
Great, I'll just make some slight adjustments on this guide and will issue a PR soon :).  I'll also remove the "require PR reviewer" option on all of our master branches

**Comment by martinatsynqfm** [comment]
@batmany13 would you still like me to review this, and add my comments?
