### ISSUE TITLE
martin: review getting-started guide

### ISSUE THREAD

**Issue by martinatsynqfm** [SYNQfm/getting-started#31]
https://github.com/SYNQfm/getting-started/tree/bruce-revamp

from @batmany13 on 2017-08-09:
![revamped_guide](https://user-images.githubusercontent.com/25246876/29517444-76555888-8675-11e7-94ed-70e18407c8b1.png)

**Comment by martinatsynqfm** [comment]
@halvardos asked me to do my review now

## differences from practice

### /README.md

- i was requested to «Get Acccess to and review API design on Stoplight» ([1](https://github.com/SYNQfm/obaku/issues/1158), [2](https://github.com/SYNQfm/obaku/issues/1160)), but then requested [not](https://github.com/SYNQfm/obaku/issues/1160#issuecomment-324876503) to do a review
- naming scheme: only some repositories are named legendary creatures. computers are named after after legendary creatures
- infrastructure maintainer is halvard. i don't think halvard does particularly much work with infrastructure
- core v2 maintainers julian, martin. i have not worked much (or at all) on this project. none of the commits in the repository that is references have been done by me
- github milestones. i can't remember these being discussed in the last three months
- milestone kickoff meeting. has there ever been one? i think epic issues have been created outside of these meetings
- «Aim for continuous deployment.» in obaku, these efforts stopped somewhere in the middle of automatically deploying a staging environment
- «Maintainers determine the release cadence but changes should be deployed at least once a week» for obaku for example, i think changes to it are deployed whenever someone wants, for some people; and some weeks have had no deployments
- «Maintain as few personal branches as possible». in obaku, there are now [75 branches](https://github.com/SYNQfm/obaku/branches). i think it may be possible to keep fewer than 75 branches
- «Keep the number of open PRs low.» there are [9 open pull requests](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+org%3Asynqfm) now. the least recently updated open pull request was updated on 2017-02-02

### /deploy.md

- «Releases are tagged and finalized on Mondays by 17:00 CET/CEST». since https://github.com/SYNQfm/obaku/releases/tag/2017-08-08, no release of obaku has been made on a monday
- «Deploy to production happens every Tuesday at 17:00 - 20:00 CET/CEST». on some tuesdays, no deployments have been made
- «Out of band deploys should only happen for critical outages or major security holes». several releases of obaku have been made that don't address any of these kinds of issues. for example https://github.com/SYNQfm/obaku/releases/tag/2017-09-06 and https://github.com/SYNQfm/obaku/releases/tag/2017-08-24
- «Our goal is continuous deployment so aim for more automation». almost no work on obaku in the last six months have resulted in fewer manual steps in its deployment procedure
- «[...] and copy the deploy procedures from the previous release to the latest release.» i usually copy the notes from the last release that _i_ made

### dev_meeting/README.md

- these meetings rarely discuess individual non-epic issues now
- deployments are not planned now
- i don't think there are any monthly reviews anymore

## obstacles to my productivity

- «Add tests as you see fit» but also «Minimum code coverage (is enforced)». is there or isn't there a minimum requirement of coverage?

## details

- «Before starting your work, do you notice a pile up of PRs? Chip in and help clear it out!» i consider reviews to be work
- i think «How we software» lacks a verb
- [API docs](https://github.com/SYNQfm/getting-started/blob/a1492c6bf9434071e5eaa809e92232f593f551a2/api.synq.fm/docs) references a resource that can not be found
- «[PRs should have] Minimum code coverage (is enforced)». what is the minimum amount?

**Comment by gsemino** [comment]
Closing this for now, let me know if any objections.
